//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class ChangerScriptRoomOne : MonoBehaviour {

	IRoomScript changer;

	public enum time {PAST =0, PRESENT = 1, FUTURE = 2};
	private time current_time;

	void Start(){
		changer = new ScriptRoomOne();
		current_time = time.PRESENT;
		//boquete.SetActive (false);
	}

	void Update(){
		if(current_time != (time) changer.getCurrentTime ())
		{
			switch(changer.getCurrentTime())
			{
			case(0):
				changer.toPast();
				break;
			case(1):
				changer.toPresent();
				break;
			case(2):
				changer.toFuture();
				break;
			}
		}

	}
}

